openapi: 3.1.0
info:
  title: API Prontuário Odontológico
  version: '1.0'
  description: API para gerenciar pacientes, agendamentos e prontuários odontológicos.

servers:
  - url: https://leandrolealwisemadness.pythonanywhere.com

paths:
  /agenda:
    get:
      operationId: listar_agenda
      summary: Listar consultas do dia
      parameters:
        - name: data
          in: query
          description: Data no formato YYYY-MM-DD
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de consultas agendadas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    paciente:
                      type: string
                    data_agenda:
                      type: string
                    observacoes:
                      type: string
    post:
      operationId: agendar_consulta
      summary: Agendar consulta para paciente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paciente_id:
                  type: integer
                data_agenda:
                  type: string
                observacoes:
                  type: string
      responses:
        '200':
          description: Consulta agendada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /paciente/{id}:
    get:
      operationId: buscar_paciente_id
      summary: Buscar dados do paciente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Informações completas do paciente e seus prontuários
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  idade:
                    type: integer
                  sexo:
                    type: string
                  telefone:
                    type: string
                  prontuarios:
                    type: array
                    items:
                      type: object
                      properties:
                        data_consulta:
                          type: string
                        diagnostico:
                          type: string
                        procedimento:
                          type: string
                        prescricao:
                          type: string
                        recomendacoes:
                          type: string
                        anexos:
                          type: string

  /paciente/nome/{nome}:
    get:
      operationId: buscar_paciente_nome
      summary: Buscar paciente pelo nome
      parameters:
        - name: nome
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de pacientes com nome correspondente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    idade:
                      type: integer
                    sexo:
                      type: string
                    telefone:
                      type: string
                    prontuarios:
                      type: array
                      items:
                        type: object
                        properties:
                          data_consulta:
                            type: string
                          diagnostico:
                            type: string
                          procedimento:
                            type: string
                          prescricao:
                            type: string
                          recomendacoes:
                            type: string
                          anexos:
                            type: string

  /pacientes:
    get:
      operationId: listar_pacientes
      summary: Listar todos os pacientes cadastrados (com ou sem filtros)
      parameters:
        - name: sexo
          in: query
          required: false
          schema:
            type: string
        - name: idade
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Lista completa ou filtrada de pacientes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    idade:
                      type: integer
                    sexo:
                      type: string
                    telefone:
                      type: string

  /prontuario:
    post:
      operationId: criar_prontuario
      summary: Criar novo prontuário odontológico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paciente_id:
                  type: integer
                diagnostico:
                  type: string
                procedimento:
                  type: string
                prescricao:
                  type: array
                  items:
                    type: string
                recomendacoes:
                  type: string
                anexos:
                  type: array
                  items:
                    type: object
                    properties:
                      descricao:
                        type: string
                      link:
                        type: string
      responses:
        '200':
          description: Prontuário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /novo_paciente:
    post:
      operationId: cadastrar_paciente
      summary: Cadastrar novo paciente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                idade:
                  type: integer
                sexo:
                  type: string
                telefone:
                  type: string
      responses:
        '200':
          description: Paciente cadastrado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  status:
                    type: string

  /paciente/{paciente_id}/prontuarios:
    get:
      operationId: buscar_prontuarios_paciente
      summary: Buscar prontuários de um paciente
      parameters:
        - name: paciente_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista de prontuários do paciente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    data_consulta:
                      type: string
                    diagnostico:
                      type: string
                    procedimento:
                      type: string
                    prescricao:
                      type: string
                    recomendacoes:
                      type: string
                    anexos:
                      type: string

  /processar_comando:
    post:
      operationId: processar_comando_voz
      summary: Processar comando de voz do assistente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comando:
                  type: string
                  description: Comando de voz a ser processado
      responses:
        '200':
          description: Resposta do assistente
          content:
            application/json:
              schema:
                type: object
                properties:
                  resposta:
                    type: string

  /admin:
    get:
      operationId: admin_dashboard
      summary: Acessar o dashboard administrativo
      responses:
        '200':
          description: Dashboard administrativo
          content:
            text/html:
              schema:
                type: string

  /admin/logs:
    get:
      operationId: view_logs
      summary: Visualizar logs do sistema
      responses:
        '200':
          description: Logs do sistema
          content:
            text/html:
              schema:
                type: string
