openapi: 3.1.0
info:
  title: API Prontuário Odontológico
  version: '1.0'
  description: API para gerenciar pacientes, agendamentos, prontuários odontológicos e imagens.

servers:
  - url: https://leandrolealwisemadness.pythonanywhere.com

paths:
  /agenda:
    get:
      operationId: listar_agenda
      summary: Listar consultas do dia
      parameters:
        - name: data
          in: query
          description: Data no formato YYYY-MM-DD
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de consultas agendadas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    paciente:
                      type: string
                    data_agenda:
                      type: string
                    observacoes:
                      type: string
    post:
      operationId: agendar_consulta
      summary: Agendar consulta para paciente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paciente_id:
                  type: integer
                data_agenda:
                  type: string
                observacoes:
                  type: string
      responses:
        '200':
          description: Consulta agendada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /paciente/{id}:
    get:
      operationId: buscar_paciente_id
      summary: Buscar dados do paciente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Informações completas do paciente e seus prontuários
          content:
            application/json:
              schema:
                type: object
                properties:
                  nome:
                    type: string
                  idade:
                    type: integer
                  sexo:
                    type: string
                  telefone:
                    type: string
                  prontuarios:
                    type: array
                    items:
                      type: object
                      properties:
                        data_consulta:
                          type: string
                        diagnostico:
                          type: string
                        procedimento:
                          type: string
                        prescricao:
                          type: string
                        recomendacoes:
                          type: string
                        anexos:
                          type: string

  /paciente/nome/{nome}:
    get:
      operationId: buscar_paciente_nome
      summary: Buscar paciente pelo nome
      parameters:
        - name: nome
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de pacientes com nome correspondente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    idade:
                      type: integer
                    sexo:
                      type: string
                    telefone:
                      type: string
                    prontuarios:
                      type: array
                      items:
                        type: object
                        properties:
                          data_consulta:
                            type: string
                          diagnostico:
                            type: string
                          procedimento:
                            type: string
                          prescricao:
                            type: string
                          recomendacoes:
                            type: string
                          anexos:
                            type: string

  /pacientes:
    get:
      operationId: listar_pacientes
      summary: Listar todos os pacientes cadastrados (com ou sem filtros)
      parameters:
        - name: sexo
          in: query
          required: false
          schema:
            type: string
        - name: idade
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Lista completa ou filtrada de pacientes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nome:
                      type: string
                    idade:
                      type: integer
                    sexo:
                      type: string
                    telefone:
                      type: string

  /prontuario:
    post:
      operationId: criar_prontuario
      summary: Criar novo prontuário odontológico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paciente_id:
                  type: integer
                diagnostico:
                  type: string
                procedimento:
                  type: string
                prescricao:
                  type: array
                  items:
                    type: string
                recomendacoes:
                  type: string
                anexos:
                  type: array
                  items:
                    type: object
                    properties:
                      descricao:
                        type: string
                      link:
                        type: string
      responses:
        '200':
          description: Prontuário criado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string

  /paciente:
    post:
      operationId: criar_paciente_api
      summary: Cadastrar ou atualizar paciente (verifica se já existe pelo nome)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nome
              properties:
                nome:
                  type: string
                  description: Nome do paciente (obrigatório)
                idade:
                  type: integer
                  description: Idade do paciente (opcional)
                sexo:
                  type: string
                  description: Sexo do paciente (opcional)
                telefone:
                  type: string
                  description: Telefone do paciente (opcional)
      responses:
        '200':
          description: Paciente cadastrado ou atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  status:
                    type: string
                  acao:
                    type: string
                    enum: [criado, atualizado]

  /paciente/atualizar:
    put:
      operationId: atualizar_paciente_api
      summary: Atualizar dados de um paciente existente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nome
              properties:
                nome:
                  type: string
                  description: Nome do paciente para busca (obrigatório)
                idade:
                  type: integer
                  description: Nova idade do paciente (opcional)
                sexo:
                  type: string
                  description: Novo sexo do paciente (opcional)
                telefone:
                  type: string
                  description: Novo telefone do paciente (opcional)
      responses:
        '200':
          description: Paciente atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  status:
                    type: string
                  acao:
                    type: string
                    enum: [atualizado, criado]
        '409':
          description: Múltiplos pacientes encontrados com nome similar
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string
                  pacientes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        nome:
                          type: string

  /paciente/{paciente_id}/prontuarios:
    get:
      operationId: buscar_prontuarios_paciente
      summary: Buscar prontuários de um paciente
      parameters:
        - name: paciente_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Lista de prontuários do paciente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    data_consulta:
                      type: string
                    diagnostico:
                      type: string
                    procedimento:
                      type: string
                    prescricao:
                      type: string
                    recomendacoes:
                      type: string
                    anexos:
                      type: string

  /processar_comando:
    post:
      operationId: processar_comando_voz
      summary: Processar comando de voz do assistente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                comando:
                  type: string
                  description: Comando de voz a ser processado
      responses:
        '200':
          description: Resposta do assistente
          content:
            application/json:
              schema:
                type: object
                properties:
                  resposta:
                    type: string

  /admin:
    get:
      operationId: admin_dashboard
      summary: Acessar o dashboard administrativo
      responses:
        '200':
          description: Dashboard administrativo
          content:
            text/html:
              schema:
                type: string

  /admin/logs:
    get:
      operationId: view_logs
      summary: Visualizar logs do sistema
      responses:
        '200':
          description: Logs do sistema
          content:
            text/html:
              schema:
                type: string

  # Novas rotas para gerenciamento de imagens
  /prontuario/{prontuario_id}/imagem:
    post:
      operationId: api_upload_imagem
      summary: Fazer upload de uma imagem para um prontuário via API (usando URL ou base64)
      parameters:
        - name: prontuario_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imagem_url:
                  type: string
                  description: URL da imagem a ser enviada (alternativa ao base64)
                imagem_base64:
                  type: string
                  description: Dados da imagem em formato base64 (alternativa à URL)
                descricao:
                  type: string
                  description: Descrição opcional da imagem
      responses:
        '200':
          description: Imagem enviada com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  sucesso:
                    type: boolean
                  mensagem:
                    type: string
                  imagem:
                    type: object
                    properties:
                      nome:
                        type: string
                      descricao:
                        type: string
                      url:
                        type: string
        '400':
          description: Erro no upload da imagem
          content:
            application/json:
              schema:
                type: object
                properties:
                  erro:
                    type: string

  /prontuario/{prontuario_id}/upload:
    post:
      operationId: upload_imagem
      summary: Fazer upload de uma imagem para um prontuário via formulário web
      parameters:
        - name: prontuario_id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                imagem:
                  type: string
                  format: binary
                  description: Arquivo de imagem a ser enviado
                descricao:
                  type: string
                  description: Descrição opcional da imagem
      responses:
        '302':
          description: Redirecionamento após upload bem-sucedido
          headers:
            Location:
              schema:
                type: string

  /static/uploads/{filename}:
    get:
      operationId: uploaded_file
      summary: Acessar uma imagem enviada
      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Arquivo de imagem
          content:
            image/*:
              schema:
                type: string
                format: binary

  /prontuario/{prontuario_id}:
    get:
      operationId: ver_prontuario
      summary: Visualizar um prontuário específico
      parameters:
        - name: prontuario_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Página do prontuário
          content:
            text/html:
              schema:
                type: string

  /admin/verificar_ids:
    get:
      operationId: verificar_ids
      summary: Verificar sequência de IDs de pacientes
      responses:
        '200':
          description: Informações sobre IDs de pacientes
          content:
            application/json:
              schema:
                type: object
                properties:
                  sequencia_atual:
                    type: object
                  ids_pacientes:
                    type: array
                    items:
                      type: integer
                  total_pacientes:
                    type: integer
                  maior_id:
                    type: integer
                  lacunas:
                    type: array
                    items:
                      type: integer

  /diagnostico/upload:
    get:
      operationId: diagnostico_upload
      summary: Verificar configurações de upload
      responses:
        '200':
          description: Informações de diagnóstico sobre upload
          content:
            application/json:
              schema:
                type: object
                properties:
                  upload_folder:
                    type: string
                  upload_folder_exists:
                    type: boolean
                  upload_folder_writable:
                    type: boolean
                  allowed_extensions:
                    type: array
                    items:
                      type: string
                  max_content_length:
                    type: integer
                  tabelas_db:
                    type: array
                    items:
                      type: string
                  test_write:
                    type: string

  /debug/pacientes:
    get:
      operationId: debug_pacientes
      summary: Depurar lista de pacientes
      responses:
        '200':
          description: Informações de debug sobre pacientes
          content:
            application/json:
              schema:
                type: object
                properties:
                  pacientes:
                    type: array
                    items:
