openapi: 3.0.1
info:
  title: API Prontuário Odontológico
  version: '1.0'
  description: API para gerenciar pacientes, agendamentos e prontuários odontológicos.

paths:
  /api/agenda:
    get:
      summary: Listar consultas do dia
      parameters:
        - name: data
          in: query
          description: Data no formato YYYY-MM-DD
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de consultas agendadas
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
    post:
      summary: Agendar consulta para paciente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paciente_id:
                  type: integer
                data_agenda:
                  type: string
                observacoes:
                  type: string
      responses:
        '200':
          description: Consulta agendada com sucesso

  /api/paciente/{id}:
    get:
      summary: Buscar dados do paciente por ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Informações completas do paciente e seus prontuários
          content:
            application/json:
              schema:
                type: object

  /api/paciente/nome/{nome}:
    get:
      summary: Buscar paciente pelo nome
      parameters:
        - name: nome
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Lista de pacientes com nome correspondente
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /api/pacientes:
    get:
      summary: Listar todos os pacientes cadastrados (com ou sem filtros)
      parameters:
        - name: sexo
          in: query
          required: false
          schema:
            type: string
        - name: idade
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Lista completa ou filtrada de pacientes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object

  /api/prontuario:
    post:
      summary: Criar novo prontuário odontológico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                paciente_id:
                  type: integer
                diagnostico:
                  type: string
                procedimento:
                  type: string
                prescricao:
                  type: array
                  items:
                    type: string
                recomendacoes:
                  type: string
                anexos:
                  type: array
                  items:
                    type: object
                    properties:
                      descricao:
                        type: string
                      link:
                        type: string
      responses:
        '200':
          description: Prontuário criado com sucesso
